name: Build and Archive

on:
  push: 
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

env:
  ARCHIVE_NAME: ${{github.event.repository.name}}-${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun (package manager)
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun i --frozen-lockfile
      - name: Build project
        run: bun run build
      - name: Create build artifact
        run: |
          mkdir artifact
          cp -R ./public ./artifact
          cp -R ./.next/standalone/. ./artifact
          mkdir -p ./artifact/static && cp -R ./.next/static/. $_
      - name: Archive artifact directory
        uses: cd ./artifact && zip -r ../${{ env.ARCHIVE_NAME }}.zip .