name: build-and-zip

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

env:
  ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ inputs.tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          fetch-tags: true
          fetch-depth: 0
      - name: Setup Bun (package manager)
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun i --frozen-lockfile
      - name: Build project
        run: bun run build
      - name: Create build artifact
        run: |
          mkdir artifact
          cp -R ./public ./artifact
          cp -R ./.next/standalone/. ./artifact
          cp -R ./.next/static ./artifact/.next
      - name: Archive artifact directory
        run: cd ./artifact && zip -r ../${{ env.ARCHIVE_NAME }}.zip .
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ARCHIVE_NAME }}.zip
          tag_name: ${{inputs.tag}}