name: Build and Archive

on:
  create: 
    
  push: 
    tags: 
      - "**"

env:
  ARCHIVE_NAME: ${{github.event.repository.name}}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun (package manager)
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun i --frozen-lockfile
      - name: Build project
        run: bun run build
      - name: Create build artifact
        run: |
          mkdir artifact
          cp -R ./public ./artifact
          cp -R ./.next/standalone/. ./artifact
          mkdir -p ./artifact/static && cp -R ./.next/static/. $_
      - name: Archive artifact directory
        run: cd ./artifact && zip -r ../${{ env.ARCHIVE_NAME }}.zip .
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ARCHIVE_NAME }}.zip