name: Tag Bump

on:
  pull_request: 
    branches: ["main"]
    types: ["closed"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tag:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: phish108/autotag-action@v1.1.64
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          with-v: TRUE