name: bump

on:
  pull_request: 
    branches: ["main"]
    types: ["closed"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tagging:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    outputs:
      tag: ${{ steps.autotagging.outputs.new-tag }}
    steps:
      - id: autotagging
        uses: phish108/autotag-action@v1.1.64
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          with-v: TRUE
  
  build-and-zip:
    needs: tagging
    permissions: 
      contents: write
    uses: ./.github/workflows/build-and-zip.yml
    with:
      tag: v${{ needs.tagging.outputs.tag }}