name: create-build-and-zip

on:
  push: 
    tags: 
      - "*"

jobs:
  create:
    permissions: 
      contents: write
    uses: ./.github/workflows/build-and-zip.yml
    with:
      tag: ${{ github.ref_name }}
    